(function(){'use strict';
var state={payload:null,shadow:null,shadowCache:{},shadowError:'',mode:'decision',horizon:'short',market:'ALL',filter:'all',query:'',choices:loadChoices(),live:null,liveError:'',liveTimer:0,liveInFlight:false};
var apiBase=String(window.WUDE_LIVE_API_BASE||'').replace(/\/+$/,'');
var labels={watch:'列入觀察',wait_entry:'等待買點',skip:'暫不考慮'};
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
function num(value,digits){var n=Number(value);return Number.isFinite(n)?n.toFixed(digits==null?1:digits):'—';}
function loadChoices(){try{return JSON.parse(localStorage.getItem('decision_hub_user_choices_v1')||'{}');}catch(_){return{};}}
function saveChoices(){localStorage.setItem('decision_hub_user_choices_v1',JSON.stringify(state.choices));}
function saveTokenFromHash(){var access=new URLSearchParams(location.hash.replace(/^#/,'' )).get('live_token');if(!access)return;localStorage.setItem('wude-live-access-token',access);localStorage.setItem('wude_live_token',access);history.replaceState(null,'',location.pathname+location.search);}
function token(){return String(localStorage.getItem('wude-live-access-token')||localStorage.getItem('wude_live_token')||'').trim();}
function reportAge(value){return value?String(value).replace('T',' '):'未提供';}
function metric(label,value,note){return'<div class="metric"><span>'+esc(label)+'</span><b>'+esc(value)+'</b><small>'+esc(note||'')+'</small></div>';}
function money(value){var n=Number(value);return Number.isFinite(n)?'NT$'+Math.round(n).toLocaleString('zh-TW'):'—';}
function shares(value){var n=Number(value);return Number.isFinite(n)?(n>0?'+':'')+Math.round(n).toLocaleString('zh-TW')+'股':'—';}
function renderStatus(){var p=state.payload||{},s=p.summary||{},r=p.readiness||{},v=r.validation_60d||r.forward_validation||{},g=r.model_graduation||{},gf=g.summary||{},tf=r.tw_official_financial||{},ti=r.tw_institutional||{},sq=r.stockq_market_context||{},ue=p.unified_evidence||{},pc=p.portfolio_control||{},answer=p.single_answer||{},ns=(p.next_session_shadow||{}).summary||{},pe=(p.prediction_engine||{}).run_summary||{},sv=(state.shadow||{}).validation||{},sd=sv.valid_trading_days||{};document.getElementById('status').innerHTML=
metric('中央判斷',(s.decision_count||0)+' 檔','涵蓋台股與美股')+
metric('多週期預判',String(pe.symbol_count||0)+' 檔',String(pe.latest_prediction_count||0)+'筆固定答案')+
metric('明日預判',String(ns.data_ready_count||0)+' 檔','偏多 '+String(ns.up_count||0)+'｜可買候選 '+String(ns.buyable_candidate_count||0))+
metric('綜合影子試走','台 '+(sd.TW||0)+'日｜美 '+(sd.US||0)+'日','20日初評｜60日人工畢業審查')+
metric('已裁決衝突',(s.resolved_conflict_count||s.conflict_count||0)+' 檔','未裁決 '+(s.unresolved_conflict_count||0)+' 檔')+
metric('60日向前驗證',(v.collected_trading_days||0)+' / '+(v.target_trading_days||60),'剩 '+(v.remaining_trading_days==null?'—':v.remaining_trading_days)+' 個交易日')+
metric('台股官方財報',(tf.available||0)+' / '+(tf.requested||0),(tf.coverage_pct==null?'尚待更新':num(tf.coverage_pct,2)+'% 完整'))+
metric('台股法人連動',(s.institution_linked_count||0)+' 檔',(ti.available?'覆蓋 '+num(ti.coverage_pct,1)+'%｜只計入一次':'覆蓋未達標｜中央隔離'))+
metric('統一證據',(ue.evidence_count||0)+' 筆','格式錯誤 '+(ue.invalid_count||0)+' 筆')+
metric('反向 ETF 連動',(s.inverse_linked_count||0)+' 檔','已通過驗證 '+(s.inverse_validated_count||0)+' 檔')+
metric('模型畢業','可審查 '+(gf.eligible_for_manual_graduation||0),'累積中 '+(gf.collecting||0)+'｜需複核 '+(gf.review_required||0))+
metric('StockQ 收盤後備援',esc(((sq.market_signal||{}).regime)||'尚待更新'),'指標 '+(sq.indicator_count||0)+'｜只補缺值、不改正式排名')+
metric('部位控制',money(pc.suggested_invested_twd||0),'等待買點不計入已投資');
var answerBox=document.getElementById('singleAnswer');answerBox.className='single-answer '+esc(answer.code||'hold_cash');answerBox.innerHTML='<span>中央唯一答案</span><b>'+esc(answer.headline||'尚無結論')+'</b><p>'+esc(answer.detail||'等待完整資料')+'</p>';
document.getElementById('updatedChip').textContent='更新 '+reportAge(p.updated_at);
var missing=p.missing_sources||[],warnings=(((r.system_guard||{}).warnings)||[]),notice=document.getElementById('notice'),messages=[];
if(missing.length)messages.push('資料源暫時缺少：'+missing.join('、')+'；相關欄位不會推測');
if((s.news_coverage_count||0)<(s.decision_count||0))messages.push('新聞掃描已完成 '+(s.news_coverage_count||0)+' / '+(s.decision_count||0)+' 檔；其餘由排程逐輪補齊，不阻斷核心判斷');
warnings.forEach(function(w){messages.push((w.title||w.code)+'：'+w.detail);});
if(messages.length){notice.hidden=false;notice.textContent=messages.join('。')+'。';}else{notice.hidden=true;}
}
function price(value){var n=Number(value);return Number.isFinite(n)?n.toLocaleString('zh-TW',{maximumFractionDigits:4}):'—';}
function horizon(item,key){var h=(item.horizons||{})[key]||{},x=h.execution||{};return'<div class="horizon"><div class="horizon-head"><span>'+esc(h.label||key)+'</span><b class="'+esc(h.recommendation||'')+'">'+esc(h.action||'資料不足')+'</b></div><div class="execution '+esc(x.code||'watch')+'">'+esc(x.label||'尚無操作判讀')+'</div><div class="levels"><div><span>買進區</span><b>'+price(h.entry_low)+'～'+price(h.entry_high)+'</b></div><div><span>停損</span><b>'+price(h.stop)+'</b></div><div><span>目標一</span><b>'+price(h.target1)+'</b></div><div><span>目標二</span><b>'+price(h.target2)+'</b></div></div><p class="execution-reason">'+esc(x.reason||'')+'</p><small>分數 '+num(h.score,1)+'｜信心 '+num(h.confidence,0)+'%</small><details class="rules"><summary>進出場規則</summary><p>進：'+esc(h.entry_rule||'尚無')+'</p><p>出：'+esc(h.exit_rule||'尚無')+'</p></details></div>';}
function conflicts(item){if(!item.conflicts||!item.conflicts.length)return'';return'<div class="conflicts">'+item.conflicts.map(function(c){return'<div class="conflict-row"><b>'+esc(c.reason)+'</b><br>規則：'+esc(c.resolution_rule)+'<br>結果：'+esc(c.resolution)+'</div>';}).join('')+'</div>';}
function evidence(item){return(item.evidence||[]).map(function(e){return'<div class="evidence-row"><div><div class="evidence-title">'+esc(e.source_label)+'・'+esc(e.horizon)+'</div><div class="evidence-reason">'+esc(e.reason)+'｜'+esc(e.status)+'｜'+esc(e.as_of||'未標示日期')+'</div></div><div class="evidence-score"><span class="'+esc(e.direction)+'">'+esc(e.direction)+'</span><br>'+num(e.strength,0)+'</div></div>';}).join('');}
function choiceButtons(item){var selected=state.choices[item.symbol]||'';return'<div class="choices">'+['watch','wait_entry','skip'].map(function(code){return'<button data-choice="'+code+'" data-symbol="'+esc(item.symbol)+'" class="'+(selected===code?'selected':'')+'">'+labels[code]+'</button>';}).join('')+'</div>'+(selected?'<div class="choice-note">你的決定：'+labels[selected]+'（只存在本機）</div>':'');}
function position(item){var rows=Object.keys(item.portfolio||{}).map(function(key){var r=item.portfolio[key]||{};return esc(key)+'：'+(r.status==='allocatable'?'上限 '+money(r.maximum_twd):'等待買點，配置 0');});return rows.length?'<div class="position"><b>部位控制：</b>'+rows.join('｜')+'；不自動下單</div>':'';}
function institutionLink(item){var x=item.institutional_link||{};if(item.market!=='TW'||!x.available)return'';var cls=x.direction==='oppose'?'risk':'support';return'<div class="institution-link '+cls+'"><b>🏛️ 官方法人已連動中央 AI</b><span>三大法人 '+shares(x.total_net_shares)+'｜外資 '+shares(x.foreign_net_shares)+'｜投信 '+shares(x.trust_net_shares)+'｜自營商 '+shares(x.dealer_net_shares)+'</span><small>'+esc(x.session_date||'未標示日期')+'・已在正式 V6 計入，中央不重複加分</small></div>';}
function nextSession(item){var x=item.next_session_prediction||{},direction=x.direction||'WAITING',cls=direction==='UP'?'up':direction==='DOWN'?'down':'',label=direction==='UP'?'📈 下一交易日預判偏多':direction==='DOWN'?'📉 下一交易日預判偏空':direction==='ABSTAIN'?'⚪ 下一交易日多空不足':direction==='INSUFFICIENT'?'⚪ 下一交易日資料不足':'🕒 等待固定收盤預判';return'<div class="next-session '+cls+'"><b>'+label+'</b><span>上漲機率估計 '+num(x.up_probability_estimate_pct,1)+'%｜可買性 '+num(x.buyability_score,1)+'｜'+esc(x.buyability_status||'等待資料')+'</span><small>不因今日上漲直接加分；趨勢、量價與資金流若支持續漲仍可入榜。追高風險只降低可買性。</small></div>';}
function predictionEngine(item){var e=item.prediction_engine||{},h=e.horizons||{},n=h.NEXT_1D||{},d5=h.UP_5D||{},d45=h.UP_45D||{},d126=h.UP_126D||{},fall=h.DOWN_14D||{};if(!Object.keys(h).length)return'<div class="next-session"><b>🕒 多週期預判等待該市場固定收盤</b><span>正式 V6 與原本紀錄不受影響</span></div>';return'<div class="next-session"><b>🧭 AI 多週期預判</b><span>明日上漲 '+num(n.probability_pct,1)+'%・可買性 '+num(n.buyability_score,1)+'｜5日預期 '+num(d5.expected_return_pct,2)+'%｜45日 '+num(d45.expected_return_pct,2)+'%｜6個月 '+num(d126.expected_return_pct,2)+'%</span><small>14日下跌風險 '+num(fall.probability_pct,1)+'%；固定答案、不讀未來結果、AI中央只讀。</small></div>';}
function liveSignal(item){var live=state.live||{},alerts=live.alerts||[],alert=null;for(var i=0;i<alerts.length;i++){if(alerts[i].market===item.market&&String(alerts[i].symbol||'').toUpperCase()===String(item.symbol||'').toUpperCase()&&(!alert||Number(alerts[i].sequence||0)>Number(alert.sequence||0)))alert=alerts[i];}var market=(((live.capital_flow||{}).markets||{})[item.market]||{}),flow=((market.windows||{})['15m']||{}),flowRow=null,flowSide='';(flow.top_inflows||[]).forEach(function(row){if(String(row.symbol||'').toUpperCase()===String(item.symbol||'').toUpperCase()){flowRow=row;flowSide='buy';}});(flow.top_outflows||[]).forEach(function(row){if(String(row.symbol||'').toUpperCase()===String(item.symbol||'').toUpperCase()){flowRow=row;flowSide='sell';}});var institution=null,institutionSide='',snapshot=live.institutional_snapshot||{},total=((snapshot.groups||{}).total||{});if(item.market==='TW'&&snapshot.ranking_eligible){(total.buys||[]).forEach(function(row){if(String(row.symbol||'').toUpperCase()===String(item.symbol||'').toUpperCase()){institution=row;institutionSide='buy';}});(total.sells||[]).forEach(function(row){if(String(row.symbol||'').toUpperCase()===String(item.symbol||'').toUpperCase()){institution=row;institutionSide='sell';}});}var group=((item.inverse_shadow||{}).group),cards=(((((live.inverse_etf_live_shadow||{}).markets||{})[item.market]||{}).cards)||[]),inverse=null;for(var j=0;j<cards.length;j++){if(cards[j].group===group){inverse=cards[j];break;}}return{alert:alert,flow:flowRow,flowSide:flowSide,institution:institution,institutionSide:institutionSide,inverse:inverse};}
function liveDecision(item){if(!state.live)return'';var signal=liveSignal(item),parts=[],risk=0,support=0;if(signal.alert){var sell=signal.alert.alert_side==='sell',value=Number(signal.alert.value||signal.alert.sell_value||signal.alert.buy_value||0);parts.push((sell?'大賣 ':'大買 ')+(item.market==='TW'?'NT$':'US$')+new Intl.NumberFormat('zh-TW',{notation:'compact',maximumFractionDigits:1}).format(value));if(sell)risk+=2;else support+=2;}if(signal.flow){parts.push('15分鐘'+(signal.flowSide==='sell'?'流出 ':'流入 ')+(item.market==='TW'?'NT$':'US$')+new Intl.NumberFormat('zh-TW',{notation:'compact',maximumFractionDigits:1}).format(Math.abs(Number(signal.flow.net_flow||0))));if(signal.flowSide==='sell')risk+=1;else support+=1;}if(signal.institution){parts.push('官方法人'+(signal.institutionSide==='sell'?'賣超 ':'買超 ')+shares(signal.institution.shares));if(signal.institutionSide==='sell')risk+=1;else support+=1;}if(signal.inverse&&Number(signal.inverse.live_score)>=60){parts.push('反向風險 '+num(signal.inverse.live_score,1));risk+=Number(signal.inverse.live_score)>=70?2:1;}if(!parts.length)return'';var code=risk>support?'risk':support>risk?'support':'watch',label=code==='risk'?'中央連動：風險升高':code==='support'?'中央連動：買方支持':'中央連動：多空交錯';return'<div class="live-shadow '+code+'"><b>'+label+'</b><span>'+esc(parts.join('｜'))+'</span><small>每10秒更新；官方法人只限台股，其餘為即時影子；不回寫正式排名或自動下單</small></div>';}
function card(item){var f=item.final||{},classes='card'+(item.conflict_count?' conflict':'')+(f.recommendation==='data_insufficient'?' blocked':'');return'<article class="'+classes+'"><div class="card-head"><div><div class="symbol">'+esc(item.market)+'・'+esc(item.symbol)+'・正式 #'+esc(item.formal_rank||'—')+'</div><div class="name">'+esc(item.name)+'</div><div class="meta">現價 '+num(item.price,2)+'｜正式分數 '+num(item.formal_score,1)+'｜'+esc(item.industry||item.asset_type||'未分類')+'</div></div><div class="decision"><b class="'+esc(f.recommendation||'')+'">'+esc(f.action||'資料不足')+'</b><small>信心 '+num(f.confidence,0)+'%</small></div></div>'+predictionEngine(item)+nextSession(item)+institutionLink(item)+liveDecision(item)+'<div class="horizons">'+horizon(item,'short')+horizon(item,'medium')+horizon(item,'long')+'</div><div class="why"><b>中央結論：</b>'+esc(f.reason||'尚無結論')+'</div>'+position(item)+conflicts(item)+(item.data_missing&&item.data_missing.length?'<div class="missing">可持續補強：'+esc(item.data_missing.join('、'))+'（不等於核心資料缺失）</div>':'')+'<details><summary>查看全部證據與日期</summary><div class="evidence">'+evidence(item)+'</div></details>'+choiceButtons(item)+'</article>';}
function rankChange(value){var n=Number(value)||0;return n>0?'<span class="rank-up">↑'+n+'</span>':n<0?'<span class="rank-down">↓'+Math.abs(n)+'</span>':'<span class="rank-flat">—</span>';}
function adjustmentPills(row){return(row.adjustments||[]).filter(function(x){return x.applicable;}).map(function(x){var p=Number(x.points)||0,cls=p>0?'positive':p<0?'negative':'';return'<span class="adjustment '+cls+'">'+esc(x.label)+' '+(x.available?(p>0?'+':'')+num(p,2):'缺資料')+'</span>';}).join('');}
function shadowCard(row){var compare=state.mode==='compare',delta=Number(row.adjustment_points)||0;return'<article class="shadow-card"><div class="shadow-card-head"><div><div class="symbol">'+esc(row.market)+'・'+esc(row.horizon_label)+'・'+esc(row.symbol)+'</div><h3>'+esc(row.name)+'</h3><div class="meta">'+esc(row.industry||row.asset_type||'未分類')+'｜影子覆蓋 '+num(row.shadow_coverage_pct,0)+'%｜信心 '+num(row.confidence,0)+'%</div></div><div class="shadow-rank">#'+esc(row.shadow_rank)+'<small>'+(compare?'相較基準 '+rankChange(row.rank_change):'綜合影子順位')+'</small></div></div><div class="score-compare"><div><span>同時段基準</span><b>#'+esc(row.baseline_rank)+'・'+num(row.baseline_score,1)+'</b></div><div><span>綜合影子</span><b>#'+esc(row.shadow_rank)+'・'+num(row.shadow_score,1)+'</b></div><div><span>影子調整</span><b class="'+(delta>0?'rank-up':delta<0?'rank-down':'rank-flat')+'">'+(delta>0?'+':'')+num(delta,2)+'</b></div></div><div class="adjustments">'+adjustmentPills(row)+'</div><small class="muted">正式總排名 #'+esc(row.formal_overall_rank||'—')+' 保持不變；缺資料不補0、不自動改權重或下單。</small></article>';}
function isETF(item){return String(item.asset_type||'').toUpperCase().indexOf('ETF')>=0;}
function executionCodes(item){return Object.keys(item.horizons||{}).map(function(key){var h=(item.horizons||{})[key]||{};return(h.execution||{}).code||'';});}
function filtered(){var rows=(state.payload&&state.payload.decisions)||[],q=state.query.trim().toUpperCase();return rows.filter(function(item){if(state.market==='ETF'&&!isETF(item))return false;if(state.market!=='ALL'&&state.market!=='ETF'&&item.market!==state.market)return false;var codes=executionCodes(item);if(state.filter==='conflict'&&!item.conflict_count)return false;if(state.filter==='entry_zone'&&!codes.some(function(c){return c==='entry_confirm'||c==='entry_wait_confirmation';}))return false;if(state.filter==='no_chase'&&codes.indexOf('no_chase')<0)return false;if(state.filter==='exit_signal'&&!codes.some(function(c){return['stop_exit','take_profit_1','take_profit_2','exit_or_avoid'].indexOf(c)>=0;}))return false;if(['all','conflict','entry_zone','no_chase','exit_signal'].indexOf(state.filter)<0&&(!item.final||item.final.recommendation!==state.filter))return false;if(q&&String(item.symbol+' '+item.name+' '+(item.industry||'')).toUpperCase().indexOf(q)<0)return false;return true;});}
function selectedShadowMarkets(){return state.market==='TW'||state.market==='US'?[state.market]:['TW','US'];}
function shadowRows(){if(!state.shadow)return[];var q=state.query.trim().toUpperCase(),rows=[];selectedShadowMarkets().forEach(function(market){var source=state.shadowCache[market+':'+state.horizon]||[];source.forEach(function(row){if(state.market==='ETF'&&!isETF(row))return;if(q&&String(row.symbol+' '+row.name+' '+(row.industry||'')).toUpperCase().indexOf(q)<0)return;rows.push(row);});});return rows;}
function loadShadowSelection(){if(!state.shadow)return Promise.resolve();var stamp=Date.now(),files=state.shadow.ranking_files||{},jobs=[];selectedShadowMarkets().forEach(function(market){var key=market+':'+state.horizon,path=((files[market]||{})[state.horizon]);if(state.shadowCache[key]||!path)return;jobs.push(fetchJSON(path,stamp).then(function(chunk){state.shadowCache[key]=chunk.rankings||[];}));});return Promise.all(jobs).then(function(){state.shadowError='';}).catch(function(error){state.shadowError=error&&error.message||'影子排名資料無法讀取';});}
function refreshShadowView(){if(state.mode==='decision'){render();return;}document.getElementById('cards').innerHTML='<div class="empty">正在載入綜合影子排名…</div>';loadShadowSelection().then(render);}
function renderLiveStatus(){var box=document.getElementById('liveLink');if(!box)return;if(state.live){var streams=state.live.streams||{},tw=streams.TW||{},us=streams.US||{};box.className='live-link ok';box.innerHTML='<b>🚨 即時資金已連動 AI 決策</b><span>台股 '+esc(tw.state||'等待')+' '+esc(tw.subscribed||0)+'檔｜美股 '+esc(us.state||'等待')+' '+esc(us.subscribed||0)+'檔｜符合訊號的個股卡會顯示即時影子結論</span>';return;}box.className='live-link warn';box.innerHTML='<b>即時資金連動：'+(token()?'等待重新連線':'尚未取得本機授權')+'</b><span>'+esc(state.liveError||'靜態 AI 決策與反向 ETF 收盤資料仍可正常使用')+'</span>'+(!token()?'<a href="live-flow.html">前往大量買賣頁完成一次性手機授權</a>':'');}
function render(){if(!state.payload)return;renderStatus();renderLiveStatus();var shadowMode=state.mode!=='decision',filters=document.getElementById('filters'),shadowControls=document.getElementById('shadowHorizons'),shadowNote=document.getElementById('shadowNote');filters.hidden=shadowMode;shadowControls.hidden=!shadowMode;shadowNote.hidden=!shadowMode;document.querySelector('.section-title h2').textContent=state.mode==='decision'?'個股決策卡':state.mode==='shadow'?'綜合影子排名':'正式／影子比較';var rows=shadowMode?shadowRows():filtered();document.getElementById('count').textContent=rows.length+' 檔';document.getElementById('cards').innerHTML=rows.length?(shadowMode?rows.map(shadowCard).join(''):rows.map(card).join('')):'<div class="empty">'+(shadowMode&&(state.shadowError||!state.shadow)?esc(state.shadowError||'綜合影子排名暫時無法讀取，正式 V6 不受影響。'):'目前篩選條件沒有資料。')+'</div>';}
function fetchJSON(path,stamp){return fetch('reports/'+path+'?v='+stamp,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error(path+' HTTP '+r.status);return r.json();});}
function load(){document.getElementById('cards').innerHTML='<div class="empty">正在載入中央決策資料…</div>';var stamp=Date.now();fetchJSON('decision_hub.json',stamp).then(function(p){var files=p.decision_files||[];if(!files.length)throw new Error('中央個股資料清單不存在');return Promise.all(files.map(function(path){return fetchJSON(path,stamp);})).then(function(chunks){p.decisions=[];chunks.forEach(function(chunk){p.decisions=p.decisions.concat(chunk.decisions||[]);});return p;});}).then(function(p){state.payload=p;return fetchJSON('comprehensive_shadow_ranking.json',stamp).catch(function(){return null;});}).then(function(shadow){state.shadow=shadow;render();void fetchLive();}).catch(function(err){document.getElementById('cards').innerHTML='<div class="empty">中央資料暫時無法讀取：'+esc(err.message)+'<br>正式排名不受影響，請稍後按更新。</div>';});}
async function fetchLive(){if(state.liveInFlight||!apiBase)return;var access=token();if(!access){state.live=null;state.liveError='請由已授權的報表入口開啟一次；授權只保存在這支手機。';renderLiveStatus();return;}state.liveInFlight=true;try{var response=await fetch(apiBase+'/api/large-buy-alerts?after=0&limit=100',{cache:'no-store',headers:{Accept:'application/json','X-Live-Token':access}}),data=await response.json().catch(function(){return{};});if(!response.ok||!data.ok)throw new Error(data.error||'即時資金資料無法取得');state.live=data;state.liveError='';render();}catch(error){state.live=null;state.liveError=error&&error.message||'即時資金資料無法取得';renderLiveStatus();}finally{state.liveInFlight=false;}}
function scheduleLive(){clearInterval(state.liveTimer);state.liveTimer=setInterval(function(){if(document.visibilityState==='visible')void fetchLive();},10000);}
document.getElementById('refresh').addEventListener('click',load);
document.getElementById('search').addEventListener('input',function(e){state.query=e.target.value;render();});
document.getElementById('viewModes').addEventListener('click',function(e){var b=e.target.closest('button[data-mode]');if(!b)return;state.mode=b.dataset.mode;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b);});refreshShadowView();});
document.getElementById('shadowHorizons').addEventListener('click',function(e){var b=e.target.closest('button[data-horizon]');if(!b)return;state.horizon=b.dataset.horizon;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b);});refreshShadowView();});
document.getElementById('markets').addEventListener('click',function(e){var b=e.target.closest('button[data-market]');if(!b)return;state.market=b.dataset.market;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b);});refreshShadowView();});
document.getElementById('filters').addEventListener('click',function(e){if(state.mode!=='decision')return;var b=e.target.closest('button[data-filter]');if(!b)return;state.filter=b.dataset.filter;this.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b);});render();});
document.getElementById('cards').addEventListener('click',function(e){var b=e.target.closest('button[data-choice]');if(!b)return;var symbol=b.dataset.symbol,choice=b.dataset.choice;if(state.choices[symbol]===choice)delete state.choices[symbol];else state.choices[symbol]=choice;saveChoices();render();});
saveTokenFromHash();load();scheduleLive();document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')void fetchLive();});window.addEventListener('beforeunload',function(){clearInterval(state.liveTimer);});
})();
