(function(){
'use strict';
var state={market:'TW',db:null,shadow:null,live:null,timer:0};
var apiBase=String(window.WUDE_LIVE_API_BASE||'').replace(/\/+$/,'');
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function n(v,d){var x=Number(v);return Number.isFinite(x)?x.toFixed(d==null?0:d):'—';}
function token(){return String(localStorage.getItem('wude-live-access-token')||localStorage.getItem('wude_live_token')||'').trim();}
function strength(v){return {index:'指數對應',sector:'產業替代',broad:'大盤替代'}[v]||v;}
function statusText(v){return {confirmed:'條件確認',small_shadow:'影子小額試走',watch:'觀察中',waiting:'目前不啟動',no_chase:'已漲多・不追價'}[v]||v;}
function renderSummary(){var s=state.db.summary||{};document.getElementById('summary').innerHTML=['全部|'+state.db.universe_count,'台股|'+s.TW,'美股|'+s.US,'產業／指數|'+((s.sector||0)+(s.index||0)),'大盤替代|'+(s.broad||0)].map(function(x){var a=x.split('|');return '<div class="metric"><span>'+e(a[0])+'</span><b>'+e(a[1])+'</b></div>';}).join('');}
function renderProducts(){document.getElementById('products').innerHTML=(state.db.products||[]).filter(function(p){return p.market===state.market;}).map(function(p){return '<div class="product"><h3>'+e(p.symbol)+'・'+e(p.name)+'</h3><span class="pill">每日 '+e(p.daily_target)+'x</span><small>'+e(p.benchmark)+'</small></div>';}).join('');}
function renderStaticShadow(){var market=(state.shadow.markets||{})[state.market]||{},c=market.current_candidates||[];document.getElementById('candidates').innerHTML=c.slice(0,6).map(function(x){var detail=x.no_chase?'反向ETF當日已達追價門檻':x.status==='confirmed'?'空頭廣度成立｜等待實價驗證':x.status==='watch'?'廣度接近門檻':'空頭廣度未成立';return '<div class="candidate '+e(x.status)+'"><h3>'+e(x.inverse_symbol)+'・'+e(x.inverse_name)+'</h3><div class="score">空方 '+n(x.bear_score,1)+' 分</div><small>'+e(detail)+'・樣本 '+e(x.constituent_count)+' 檔</small><div class="components"><span>下跌廣度 '+n((x.evidence||{}).negative_breadth_pct,1)+'%</span><span>中位漲跌 '+n((x.evidence||{}).median_change_pct,2)+'%</span><span>跌破20日 '+n((x.evidence||{}).breakdown_pct,1)+'%</span><span>反向ETF當日 '+n(x.product_session_change_pct,2)+'%</span></div></div>';}).join('')||'<div class="muted">等待完成收盤資料。</div>';var summary=market.summary||{};document.getElementById('performance').innerHTML=['1','2','3','5'].map(function(day){var x=summary[day]||{};return '<div class="metric"><span>第 '+day+' 交易日・'+n(x.samples)+' 樣本</span><b>'+n(x.average_return_pct,2)+'%</b><small>勝率 '+n(x.win_rate_pct,1)+'%</small></div>';}).join('');}
function renderLive(){var root=state.live,market=root&&root.markets&&root.markets[state.market],status=document.getElementById('liveStatus');if(!root){status.textContent=token()?'即時資料連線中…':'尚未取得本人即時授權；下方收盤資料仍可正常查看。';document.getElementById('liveCards').innerHTML='<div class="muted">等待即時資料。</div>';return;}status.textContent='15分鐘資金流｜市場主動買進 '+n(market&&market.market_buy_ratio_pct,1)+'%｜正向廣度 '+n(market&&market.market_positive_breadth_pct,1)+'%';var cards=(market&&market.cards)||[];document.getElementById('liveCards').innerHTML=cards.slice(0,6).map(function(x){var c=x.components||{},missing=(x.data_missing||[]).join('、');return '<div class="candidate '+e(x.status)+'"><h3>'+e(x.inverse_symbol)+'・'+e(x.inverse_name)+'</h3><div class="score">可用 '+n(x.live_score,1)+' 分</div><small>'+e(statusText(x.status))+'</small><div class="components"><span>實測配對 '+n(c.mapping_quality,1)+'</span><span>空頭廣度 '+n(c.bearish_breadth,1)+'</span><span>賣壓 '+n(c.sell_flow,1)+'</span><span>15分大賣 '+n(c.large_sell_alerts_15m)+' 次</span></div>'+(missing?'<small style="margin-top:9px">缺資料：'+e(missing)+'</small>':'')+'</div>';}).join('')||'<div class="muted">市場尚未建立可用族群。</div>';}
function renderMappings(){var q=document.getElementById('search').value.trim().toLowerCase(),rows=(state.db.mappings||[]).filter(function(x){return x.market===state.market;}).filter(function(x){return !q||[x.symbol,x.name,x.theme,x.industry,x.inverse_symbol].join(' ').toLowerCase().includes(q);});document.getElementById('mappings').innerHTML=rows.map(function(x){var corr=x.negative_correlation_60d==null?'等待日線對齊':'60日負相關 '+n(x.negative_correlation_60d,1)+'%';return '<tr><td><b>'+e(x.symbol)+'・'+e(x.name)+'</b><small>'+e(x.theme||x.industry)+'</small></td><td><b>'+e(x.inverse_symbol)+'</b><small>'+e(x.daily_target)+'x 每日目標</small></td><td><b>'+n(x.mapping_quality_score,1)+'</b><small>'+e(corr)+'・'+n(x.correlation_samples)+'筆</small></td><td><span class="pill">'+e(strength(x.mapping_strength))+'</span></td><td>'+e(x.rationale)+'</td></tr>';}).join('');}
function render(){if(!state.db||!state.shadow)return;renderSummary();renderProducts();renderStaticShadow();renderLive();renderMappings();document.querySelectorAll('[data-market]').forEach(function(b){b.classList.toggle('active',b.dataset.market===state.market);});}
async function fetchLive(){var access=token();if(!access){renderLive();return;}try{var response=await fetch(apiBase+'/api/large-buy-alerts?after=0&limit=1',{cache:'no-store',headers:{Accept:'application/json','X-Live-Token':access}}),payload=await response.json();if(!response.ok||!payload.ok)throw Error(payload.error||'即時資料無法取得');state.live=payload.inverse_etf_live_shadow||null;renderLive();}catch(error){document.getElementById('liveStatus').textContent='即時資料等待重新連線；收盤影子不受影響。';}}
Promise.all([fetch('reports/inverse_etf_database.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('資料庫讀取失敗');return r.json();}),fetch('reports/inverse_etf_shadow.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('影子資料讀取失敗');return r.json();})]).then(function(x){state.db=x[0];state.shadow=x[1];render();fetchLive();state.timer=setInterval(function(){if(document.visibilityState==='visible')fetchLive();},10000);}).catch(function(err){document.getElementById('summary').innerHTML='<div class="risk">'+e(err.message)+'</div>';});
document.querySelectorAll('[data-market]').forEach(function(b){b.addEventListener('click',function(){state.market=b.dataset.market;render();});});
document.getElementById('search').addEventListener('input',renderMappings);
window.addEventListener('beforeunload',function(){clearInterval(state.timer);});
})();
