(function(){
'use strict';
var state={market:'TW',window:'15m',cursor:0,alerts:[],payload:null,timer:0,inFlight:false,stopped:false,sound:localStorage.getItem('flow-alert-sound')==='1',primed:false,pairingRequest:''};
var apiBase=String(window.WUDE_LIVE_API_BASE||'').replace(/\/+$/,'');
var $=function(id){return document.getElementById(id);};
var escapeHtml=function(value){return String(value===undefined||value===null?'—':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});};
var num=function(value,digits){var n=Number(value);return Number.isFinite(n)?n.toLocaleString('zh-TW',{minimumFractionDigits:digits||0,maximumFractionDigits:digits===undefined?2:digits}):'—';};
var money=function(value,market){var n=Number(value);if(!Number.isFinite(n))return '—';var sign=n>0?'+':n<0?'−':'';return sign+(market==='TW'?'NT$':'US$')+new Intl.NumberFormat('zh-TW',{notation:'compact',maximumFractionDigits:1}).format(Math.abs(n));};
var thresholdMoney=function(value,market){var n=Number(value);return Number.isFinite(n)?(market==='TW'?'NT$':'US$')+new Intl.NumberFormat('zh-TW',{notation:'compact',maximumFractionDigits:1}).format(n):'未啟用';};
var time=function(value){if(!value)return '—';var date=new Date(value);return Number.isNaN(date.getTime())?String(value):date.toLocaleTimeString('zh-TW',{hour12:false,timeZone:'Asia/Taipei'});};
function saveTokenFromHash(){var token=new URLSearchParams(location.hash.replace(/^#/,'')).get('live_token');if(!token)return;localStorage.setItem('wude-live-access-token',token);localStorage.setItem('wude_live_token',token);history.replaceState(null,'',location.pathname+location.search);}
function token(){return String(localStorage.getItem('wude-live-access-token')||localStorage.getItem('wude_live_token')||'').trim();}
function streamLabel(stream){if(!stream)return '等待啟動';if(stream.state==='premarket_connected')return '盤前監控中 '+(stream.subscribed||0)+'檔';if(stream.state==='connected')return '正式盤監控中 '+(stream.subscribed||0)+'檔';if(stream.state==='waiting_market_open')return '等待下次開盤';if(stream.state==='blocked')return '行情方案受限';if(stream.state==='disabled')return '已停用';if(stream.state==='reconnecting')return '重新連線中';return stream.state||'連線中';}
function phaseLabel(value){return value==='premarket'?'盤前':value==='regular'?'正式盤':'休市';}
function beep(){if(!state.sound)return;try{var AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return;var ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.18,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.3);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.32);osc.onended=function(){ctx.close();};}catch(error){}if('vibrate'in navigator)navigator.vibrate([160,80,160]);}
function renderStreams(){var data=state.payload||{},streams=data.streams||{},universe=data.universe||{};$('streams').innerHTML=['TW','US'].map(function(market){var row=streams[market]||{},className=(row.state==='connected'||row.state==='premarket_connected')?' connected':row.state==='blocked'?' blocked':'';return '<article class="stream'+className+'"><span>'+(market==='TW'?'台股・富邦':'美股・Alpaca SIP')+'</span><b>'+escapeHtml(streamLabel(row))+' / '+escapeHtml(universe[market]||0)+'檔</b>'+(row.error?'<small>'+escapeHtml(row.error)+'</small>':'')+'</article>';}).join('');}
function renderAlertPolicy(){var policy=state.payload&&state.payload.policy||{},general=policy.general_single_thresholds||{},major=policy.major_single_thresholds||{},block=policy.block_single_thresholds||{};$('alertPolicy').textContent='台股單筆：'+thresholdMoney(general.TW,'TW')+'、'+thresholdMoney(major.TW,'TW')+'、'+thresholdMoney(block.TW,'TW')+'｜美股巨額單筆：'+thresholdMoney(block.US,'US')+'｜買進與賣出同步通知';}
function renderRow(row,index,market,rowType,direction){var isTheme=rowType==='theme';var count=isTheme?(row.positive_symbols||row.negative_symbols||0)+'/'+(row.member_count||0)+'檔'+(row.resonance?'・3檔共振':''):(row.theme||'—')+'・持續'+num(row.persistence_pct,0)+'%・信心'+num(row.confidence,0);var title=isTheme?(row.theme||'未分類族群'):(row.name||row.symbol||'未命名')+'・'+(row.symbol||'—');var out=direction==='out';var ratio=out?100-Number(row.buy_ratio_pct||0):Number(row.buy_ratio_pct||0);return '<div class="row"><div><b>#'+(index+1)+' '+escapeHtml(title)+'</b><small>'+escapeHtml(count)+'</small></div><span class="'+(out?'negative':'positive')+'">'+escapeHtml(money(row.net_flow,market))+'<small>'+(out?'賣出':'買進')+num(ratio,1)+'%</small></span></div>';}
function listCard(title,rows,market,rowType,direction,empty){return '<article class="list-card"><h3>'+title+'</h3>'+(rows.length?rows.slice(0,5).map(function(row,index){return renderRow(row,index,market,rowType,direction);}).join(''):'<div class="empty">'+empty+'</div>')+'</article>';}
function flowDirection(flow){var directional=Math.abs(Number(flow&&flow.buy_value||0))+Math.abs(Number(flow&&flow.sell_value||0));return directional>0?(flow.direction||'多空拉鋸'):'暫無資金方向';}
function renderFlow(){var marketData=state.payload&&state.payload.capital_flow&&state.payload.capital_flow.markets&&state.payload.capital_flow.markets[state.market];var flow=marketData&&marketData.windows&&marketData.windows[state.window];if(!flow){$('flowSummary').innerHTML='<div class="empty">市場開盤並收到逐筆成交後，開始累積資金流統計。</div>';$('flowLists').innerHTML='';return;}var saved=marketData.premarket_summary&&marketData.premarket_summary.windows&&marketData.premarket_summary.windows[state.window],savedText=saved?'｜盤前摘要 '+money(saved.net_flow,'US')+'・'+num(saved.trade_count,0)+'筆':'';$('flowSummary').innerHTML='<article class="metric"><span>市場方向</span><b>'+escapeHtml(flowDirection(flow))+'</b><small>'+escapeHtml((marketData.source||'—')+'・'+phaseLabel(marketData.session_phase))+escapeHtml(savedText)+'</small></article><article class="metric"><span>推估淨流向</span><b class="'+(Number(flow.net_flow)>=0?'positive':'negative')+'">'+escapeHtml(money(flow.net_flow,state.market))+'</b><small>主動買進 '+num(flow.buy_ratio_pct,1)+'%</small></article><article class="metric"><span>個股廣度</span><b>'+num(flow.positive_breadth_pct,1)+'%</b><small>'+(flow.positive_symbols||0)+'檔流入／'+(flow.negative_symbols||0)+'檔流出</small></article><article class="metric"><span>有效範圍</span><b>'+num(flow.active_symbols,0)+'檔</b><small>'+num(flow.trade_count,0)+'筆・排除'+num(flow.filtered_trade_count,0)+'筆</small></article>';$('flowLists').innerHTML=listCard('🔥 族群流入排名（按淨流金額）',flow.amount_theme_inflows||flow.theme_inflows||[],state.market,'theme','in','目前尚無持續流入族群。')+listCard('🧊 族群流出排名（按淨流金額）',flow.amount_theme_outflows||flow.theme_outflows||[],state.market,'theme','out','目前尚無持續流出族群。')+listCard('📈 個股流入排名（按淨流金額）',flow.amount_top_inflows||flow.top_inflows||[],state.market,'stock','in','等待足夠成交建立流入排序。')+listCard('📉 個股流出排名（按淨流金額）',flow.amount_top_outflows||flow.top_outflows||[],state.market,'stock','out','目前尚無明顯流出個股。');}
function renderAlerts(){var rows=state.alerts;$('alerts').innerHTML=rows.length?rows.map(function(row){var sell=row.alert_side==='sell',value=Number((sell?row.sell_value:row.buy_value)||row.value||0),ratio=sell?Number(row.aggressive_sell_ratio_pct||100-Number(row.aggressive_buy_ratio_pct||0)):Number(row.aggressive_buy_ratio_pct||0),marketText=row.market==='TW'?'台股':'美股'+(row.session_phase==='premarket'?'・盤前':'・正式盤'),alertLabel=row.is_block_trade&&row.block_trade_label?row.block_trade_label:row.trigger_label;return '<article class="alert'+(sell?' sell':'')+'"><div class="alert-title"><span class="market">'+marketText+'</span><b>'+escapeHtml((row.name||row.symbol)+'・'+row.symbol)+'</b><em>'+escapeHtml(alertLabel||'大量'+(sell?'賣出':'買進'))+'</em></div><div class="alert-meta"><span>成交價 <b>'+num(row.price)+'</b></span><span>主動'+(sell?'賣出 ':'買進 ')+money(value,row.market)+'</span><span>'+(row.trade_count||1)+'筆／'+num(ratio,1)+'%</span><time>'+escapeHtml(time(row.detected_at))+'</time></div></article>';}).join(''):'<div class="empty">符合門檻的大買或大賣訊號會顯示在這裡。</div>';}
function shadowPick(row){var adjustment=Number(row.flow_adjustment_points||0),reasons=(row.reasons||[]).join('、');return '<div class="shadow-pick"><b>#'+escapeHtml(row.rank)+'</b><div><b>'+escapeHtml((row.name||row.symbol)+'・'+row.symbol)+'</b><small>基準 '+num(row.base_score,1)+(reasons?'｜'+escapeHtml(reasons):'')+'</small></div><em>'+(adjustment?(adjustment>0?'+':'')+num(adjustment,0):num(row.shadow_score,1))+'</em></div>';}
function performanceCard(label,row){row=row||{};var samples=Number(row.samples||0),rate=Number(row.success_rate_pct),avg=Number(row.average_directional_return_pct);return '<article class="metric"><span>'+escapeHtml(label)+'</span><b class="'+(Number.isFinite(avg)?avg>=0?'positive':'negative':'')+'">'+(samples&&Number.isFinite(rate)?num(rate,1)+'%':'累積中')+'</b><small>'+samples+'筆｜平均方向報酬 '+(samples&&Number.isFinite(avg)?(avg>=0?'+':'')+num(avg,2)+'%':'—')+'</small></article>';}
function calendarLabel(calendar){calendar=calendar||{};var status=String(calendar.status||'');if(calendar.available&&status.indexOf('conservative_union')>=0)return '官方日曆雙來源差異・保守排除';if(calendar.available)return '官方交易日曆已驗證';if(status.indexOf('loading')>=0)return '官方交易日曆載入中';return '官方交易日曆缺資料・日序結算暫停';}
function renderShadow(){var root=state.payload&&state.payload.flow_weight_shadow,market=root&&root.markets&&root.markets[state.market],summary=market&&market.summary,policy=root&&root.policy||{};if(!market){$('shadowSummary').innerHTML='<span class="badge">等待影子資料</span>';$('shadowPerformance').innerHTML='<div class="empty">等待有效訊號後開始分段統計。</div>';$('shadowRanks').innerHTML='<div class="empty">即時後端更新後開始顯示。</div>';return;}var horizons=(market.signal_performance&&market.signal_performance.horizons)||{},storageBadge=policy.storage_persistent?'持久儲存正常':'儲存未持久化・本次不計入驗證';$('shadowSummary').innerHTML='<span class="badge">'+escapeHtml(state.market==='TW'?'台股獨立帳本':'美股獨立帳本')+'</span><span class="badge">'+escapeHtml(calendarLabel(market.calendar))+'</span><span class="badge">'+escapeHtml(storageBadge)+'</span><span class="badge">有效 '+num(summary.valid_trading_days,0)+' / 5 日</span><span class="badge">有效訊號 '+num(summary.valid_signals,0)+' / 200</span><span class="badge">正式排名鎖定</span>';$('shadowPerformance').innerHTML=performanceCard('訊號後5分鐘',horizons['5m'])+performanceCard('訊號後15分鐘',horizons['15m'])+performanceCard('訊號後60分鐘',horizons['60m'])+performanceCard('當日收盤',horizons.eod)+performanceCard('第1交易日',horizons.day1)+performanceCard('第3交易日',horizons.day3)+performanceCard('第5交易日',horizons.day5);$('shadowRanks').innerHTML='<div class="shadow-column"><h3>A｜正式 V6 基準</h3>'+((market.baseline_top10||[]).slice(0,5).map(shadowPick).join('')||'<div class="empty">等待排名資料</div>')+'</div><div class="shadow-column"><h3>B｜資金流影子 ±3點</h3>'+((market.shadow_top10||[]).slice(0,5).map(shadowPick).join('')||'<div class="empty">等待有效訊號</div>')+'</div>';}
function render(){renderStreams();renderAlertPolicy();renderFlow();renderShadow();renderAlerts();}
function showPairing(show){$('pairingBox').hidden=!show;}
function pairingStatus(message,error){$('pairingStatus').textContent=message;$('pairingStatus').style.color=error?'#fb7185':'#7dd3fc';}
function showError(message){$('errorBox').innerHTML=message?'<div class="error">'+escapeHtml(message)+'</div>':'';}
async function requestPairing(){var button=$('pairRequestButton');button.disabled=true;pairingStatus('正在把驗證碼傳到你的即時警報 Telegram…',false);try{var response=await fetch(apiBase+'/api/device-auth/request',{method:'POST',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json'},body:'{}'}),data=await response.json().catch(function(){return {};});if(!response.ok||!data.ok)throw new Error(data.error||'驗證碼傳送失敗');state.pairingRequest=String(data.request_id||'');if(!state.pairingRequest)throw new Error('伺服器沒有建立驗證請求');pairingStatus('驗證碼已傳送；請查看 Telegram，輸入6位數後按「完成授權」。',false);$('pairCode').focus();}catch(error){pairingStatus(error&&error.message||'驗證碼傳送失敗',true);}finally{button.disabled=false;}}
async function verifyPairing(){var code=String($('pairCode').value||'').replace(/\D/g,'');if(!state.pairingRequest){pairingStatus('請先按「傳送驗證碼」。',true);return;}if(code.length!==6){pairingStatus('請輸入 Telegram 收到的6位數驗證碼。',true);return;}var button=$('pairVerifyButton');button.disabled=true;pairingStatus('正在完成這支手機的唯讀授權…',false);try{var response=await fetch(apiBase+'/api/device-auth/verify',{method:'POST',cache:'no-store',headers:{'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({request_id:state.pairingRequest,code:code})}),data=await response.json().catch(function(){return {};});if(!response.ok||!data.ok||!data.device_token)throw new Error(data.error||'手機授權失敗');localStorage.setItem('wude-live-access-token',data.device_token);localStorage.setItem('wude_live_token',data.device_token);state.pairingRequest='';$('pairCode').value='';showPairing(false);showError('');$('syncStatus').textContent='授權完成，正在連線';state.cursor=0;state.alerts=[];await fetchData();}catch(error){pairingStatus(error&&error.message||'手機授權失敗',true);}finally{button.disabled=false;}}
async function fetchData(){if(state.inFlight)return true;state.inFlight=true;try{var access=token();if(!access){showPairing(true);throw new Error('這支手機尚未完成一次性唯讀授權。');}var response=await fetch(apiBase+'/api/large-buy-alerts?after='+state.cursor+'&limit=50',{cache:'no-store',headers:{'Accept':'application/json','X-Live-Token':access}});var data=await response.json().catch(function(){return {};});if(response.status===401){localStorage.removeItem('wude-live-access-token');localStorage.removeItem('wude_live_token');showPairing(true);}if(!response.ok||!data.ok)throw new Error(data.error||'即時資金流暫時無法取得');showPairing(false);var incoming=Array.isArray(data.alerts)?data.alerts:[];var hadPrimed=state.primed;if(incoming.length){var map=new Map(state.alerts.map(function(row){return [row.sequence,row];}));incoming.forEach(function(row){map.set(row.sequence,row);});state.alerts=Array.from(map.values()).sort(function(a,b){return b.sequence-a.sequence;}).slice(0,50);state.cursor=Math.max.apply(Math,[state.cursor].concat(incoming.map(function(row){return Number(row.sequence)||0;})));if(hadPrimed)beep();}state.cursor=Math.max(state.cursor,Number(data.latest_sequence)||0);state.payload=data;state.primed=true;showError('');$('syncStatus').textContent='最近同步 '+new Date().toLocaleTimeString('zh-TW',{hour12:false});render();return true;}catch(error){showError(error&&error.message||'即時資金流暫時無法取得');$('syncStatus').textContent='等待重新連線';return false;}finally{state.inFlight=false;}}
function schedule(delay){clearTimeout(state.timer);state.timer=setTimeout(run,delay);}
async function run(){if(state.stopped)return;if(document.visibilityState!=='visible'){schedule(1000);return;}var success=await fetchData();if(!state.stopped)schedule(success?10000:30000);}
function bindTabs(id,key,attribute){$(id).addEventListener('click',function(event){var button=event.target.closest('button');if(!button)return;state[key]=button.getAttribute(attribute);Array.from($(id).querySelectorAll('button')).forEach(function(item){item.classList.toggle('active',item===button);});render();});}
saveTokenFromHash();bindTabs('marketTabs','market','data-market');bindTabs('windowTabs','window','data-window');$('soundButton').classList.toggle('enabled',state.sound);$('soundButton').textContent=state.sound?'🔕 關閉聲音':'開啟聲音';$('soundButton').addEventListener('click',function(){state.sound=!state.sound;localStorage.setItem('flow-alert-sound',state.sound?'1':'0');this.classList.toggle('enabled',state.sound);this.textContent=state.sound?'🔕 關閉聲音':'開啟聲音';if(state.sound)beep();});$('refreshButton').addEventListener('click',function(){void fetchData();});$('pairRequestButton').addEventListener('click',function(){void requestPairing();});$('pairVerifyButton').addEventListener('click',function(){void verifyPairing();});$('pairCode').addEventListener('keydown',function(event){if(event.key==='Enter')void verifyPairing();});document.addEventListener('visibilitychange',function(){if(document.visibilityState==='visible')void run();});window.addEventListener('beforeunload',function(){state.stopped=true;clearTimeout(state.timer);});if(!token())showPairing(true);void run();
})();
