(function(){'use strict';
var REPORT=null,GROUP='TW_STOCK',KIND='forecast';
function esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function num(v,d){var n=Number(v);return Number.isFinite(n)?n.toLocaleString('zh-TW',{minimumFractionDigits:d||0,maximumFractionDigits:d||0}):'—'}
function metric(t,v){return '<div class="metric"><span>'+esc(t)+'</span><b>'+esc(v)+'</b></div>'}
function directionClass(v){return v==='UP'?'up':v==='DOWN'?'down':'waiting'}
function directionLabel(v){return v==='UP'?'📈 預判偏多':v==='DOWN'?'📉 預判偏空':v==='ABSTAIN'?'⚪ 多空不足':v==='INSUFFICIENT'?'⚪ 資料不足':'🕒 等待收盤'}
function statusLabel(v){return {candidate_wait_live_confirmation:'🟡 明日可買候選・等盤中確認',data_insufficient:'⚪ 資料不足',risk_blocked:'🔴 風險阻擋',forecast_down:'📉 預判偏空',observe:'⚪ 觀察',waiting_close_snapshot:'🕒 等固定收盤'}[v]||v||'—'}
function renderSummary(){var s=REPORT.summary||{},v=REPORT.validation||{},days=v.valid_trading_days||{};document.getElementById('summary').innerHTML=metric('固定候選池',num(s.input_count)+'檔')+metric('資料可預判',num(s.data_ready_count)+'檔')+metric('預判偏多',num(s.up_count)+'檔')+metric('向前驗證',num(days.TW)+'台股日／'+num(days.US)+'美股日');document.getElementById('status').textContent='更新：'+(REPORT.updated_at||'—')+'｜模型：'+(REPORT.model_version||'—')+'｜目前只在隔離影子累積，未取代正式排名。'}
function card(r){var rank=KIND==='forecast'?r.forecast_rank:r.buyability_rank,change=Number(r.same_session_change_pct),changeText=Number.isFinite(change)?(change>=0?'+':'')+num(change,2)+'%':'—',reasons=(r.chase_risk_reasons||[]).join('；')||'沒有額外追高／落刀折減',continuation=(r.continuation_evidence_reasons||[]).join('、')||'尚未形成獨立續漲確認';return '<article class="candidate"><div class="rank">#'+esc(rank)+'</div><h3>'+esc(r.name)+'・'+esc(r.symbol)+'</h3><span class="pill '+directionClass(r.direction)+'">'+directionLabel(r.direction)+'</span><div class="scores"><div><small>明日上漲機率估計</small><b class="'+directionClass(r.direction)+'">'+num(r.up_probability_estimate_pct,1)+'%</b></div><div><small>明日可買性</small><b>'+num(r.buyability_score,1)+'</b></div><div><small>預判分</small><b>'+num(r.forecast_score,1)+'</b></div><div><small>資料完整度</small><b>'+num(r.data_quality_pct,1)+'%</b></div></div><div class="pill">'+esc(statusLabel(r.buyability_status))+'</div><p class="reasons">當日漲跌 '+esc(changeText)+'；不因上漲直接加分。獨立續漲證據：'+esc(continuation)+'。追高／落刀只扣可買性 '+num(r.chase_risk_penalty_points,1)+'分；'+esc(reasons)+'</p><div class="current-rank">目前強勢資料僅作輔助；正式V6排名未改。</div></article>'}
function render(){if(!REPORT)return;var group=(REPORT.groups||{})[GROUP]||{},rows=(group[KIND]||[]).slice(0,10);document.getElementById('candidates').innerHTML=rows.map(card).join('')||'<div class="note">這一組尚未取得固定收盤預判。</div>'}
document.querySelectorAll('#marketTabs button').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('#marketTabs button').forEach(function(x){x.classList.remove('active')});button.classList.add('active');GROUP=button.dataset.group;render()})});
document.querySelectorAll('#rankTabs button').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('#rankTabs button').forEach(function(x){x.classList.remove('active')});button.classList.add('active');KIND=button.dataset.kind;render()})});
fetch('reports/next_session_shadow_ranking.json?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(function(data){REPORT=data;renderSummary();render()}).catch(function(error){document.getElementById('status').textContent='隔離預判報表尚未產生：'+error.message});
})();
